# Generated by Django 4.2.14 on 2024-07-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
